apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-site
  namespace: argo
spec:
  project: personal-site
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-site
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/raphaelreyna/personal-site.git
      targetRevision: master
      path: deploy/manifests/index
    - repoURL: https://github.com/raphaelreyna/personal-site.git
      targetRevision: master
      path: deploy/manifests/latte-demo
    - repoURL: https://github.com/raphaelreyna/personal-site.git
      targetRevision: master
      path: deploy/manifests/subseries