name: "Build, Push and Deploy"
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_PATH: deploy/manifests/deployment.yaml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          branch: master

      - name: Compile resume
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: resume
          root_file: raphael_reyna_short.tex

      - name: Get version and image
        run: |
          export VERSION=$(git describe --tags --abbrev=0)
          echo VERSION=$VERSION >> $GITHUB_ENV
          echo IMAGE=${{ vars.DOCKER_HUB_USER }}/personal-site:$VERSION >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

      - name: Update deployment image
        uses: mikefarah/yq@master
        with:
          cmd: yq e '.spec.template.spec.containers[0].image = "${{ env.IMAGE }}"' -i deploy/manifests/index/deployment.yaml
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master